repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.3
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: local
    hooks:
      - id: create-examples
        name: Create Examples
        entry: >
          bash -c "
          uv run python -m axi4lite_reg_generator example/inputs/example.json --output example/outputs/example &&
          git add example/outputs/* example/inputs/*
          "
        language: system
        pass_filenames: false
        always_run: true