[tool.poetry]
name = "axi4lite_reg_generator"
version = "0.1.0"
description = "Template based VHDL register generator"
authors = ["Kyle O'Brien <kyle@keelfw.com>"]
license = "lgpl"
readme = "README.md"
packages = [
    { include = "axi4lite_reg_generator" }
]

[tool.poetry.dependencies]
python = "^3.8"  # Adjust to your required Python version
attrs = "24.2.0"
exceptiongroup = "1.2.2"
iniconfig = "2.0.0"
Jinja2 = "3.1.4"
jsonschema = "4.23.0"
jsonschema-specifications = "2023.12.1"
MarkupSafe = "2.1.5"
packaging = "24.1"
pluggy = "1.5.0"
referencing = "0.35.1"
rpds-py = "0.20.0"
tomli = "2.0.1"
schema = "^0.7.7"

[tool.poetry.dev-dependencies]
# You can include other dev dependencies here
ruff = "0.6.1"
pytest = "8.3.3"
cocotb = "1.9.1"
cocotb-bus = "0.2.1"
cocotb-test = "^0.2.5"

[tool.poetry.scripts]
test = "pytest:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
branch = true
source = ["src"]

[tool.coverage.report]
fail_under = 80
show_missing = true

[tool.mypy]
files = "src tests"
ignore_missing_imports = true

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]

[tool.ruff.format]
quote-style = "single"
