/* Copyright (C) 2025 KEELFW
*
* This library is free software; you can redistribute it and/or
* modify it under the terms of the GNU Lesser General Public
* License as published by the Free Software Foundation; either
* version 2.1 of the License, or (at your option) any later version.
*
* This library is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
* Lesser General Public License for more details.
*
* You should have received a copy of the GNU Lesser General Public
* License along with this library; if not, write to the Free Software
* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
*
* See LICENSE file for full license details.
*
* This code was automatically generated by:
*   axi4lite_reg_generator v1.5.0
*
*/

#ifndef __EXAMPLE_H__
#define __EXAMPLE_H__

/* External to this header file, the base address for the register space need to be defined
#define EXAMPLE_BASE_ADDR 0x00000000
*/

// Register Addresses
#define REG_TEST_REGISTER_ADDR (EXAMPLE_BASE_ADDR + 0)
#define REG_SCRATCH_REGISTER_ADDR (EXAMPLE_BASE_ADDR + 4)
#define REG_REGISTER_WITH_FIELDS_ADDR (EXAMPLE_BASE_ADDR + 64)


// Shift / Mask values for packed registers


#define REG_REGISTER_WITH_FIELDS_REG3_MASK 0x00007000
#define REG_REGISTER_WITH_FIELDS_REG3_SHIFT 12
#define REG_REGISTER_WITH_FIELDS_REG8_MASK 0x00000FF0
#define REG_REGISTER_WITH_FIELDS_REG8_SHIFT 4
#define REG_REGISTER_WITH_FIELDS_REG4_MASK 0x0000000F
#define REG_REGISTER_WITH_FIELDS_REG4_SHIFT 0




// Getter / Setter Macros


#define REG_REGISTER_WITH_FIELDS_GET_REG3(val) (((val) & REG_REGISTER_WITH_FIELDS_REG3_MASK) >> REG_REGISTER_WITH_FIELDS_REG3_SHIFT)
#define REG_REGISTER_WITH_FIELDS_SET_REG3(val) (((val) << REG_REGISTER_WITH_FIELDS_REG3_SHIFT) & REG_REGISTER_WITH_FIELDS_REG3_MASK)
#define REG_REGISTER_WITH_FIELDS_GET_REG8(val) (((val) & REG_REGISTER_WITH_FIELDS_REG8_MASK) >> REG_REGISTER_WITH_FIELDS_REG8_SHIFT)
#define REG_REGISTER_WITH_FIELDS_SET_REG8(val) (((val) << REG_REGISTER_WITH_FIELDS_REG8_SHIFT) & REG_REGISTER_WITH_FIELDS_REG8_MASK)
#define REG_REGISTER_WITH_FIELDS_GET_REG4(val) (((val) & REG_REGISTER_WITH_FIELDS_REG4_MASK) >> REG_REGISTER_WITH_FIELDS_REG4_SHIFT)
#define REG_REGISTER_WITH_FIELDS_SET_REG4(val) (((val) << REG_REGISTER_WITH_FIELDS_REG4_SHIFT) & REG_REGISTER_WITH_FIELDS_REG4_MASK)




#endif
// SHA-256: b5b3ce3d888488a37fe448d8a88cfae6e301e128f90b166635c6d06cc0ee98a7