/* Copyright (C) 2025 KEELFW
*
* This library is free software; you can redistribute it and/or
* modify it under the terms of the GNU Lesser General Public
* License as published by the Free Software Foundation; either
* version 2.1 of the License, or (at your option) any later version.
*
* This library is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
* Lesser General Public License for more details.
*
* You should have received a copy of the GNU Lesser General Public
* License along with this library; if not, write to the Free Software
* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
*
* See LICENSE file for full license details.
*
* This code was automatically generated by:
*   axi4lite_reg_generator v{{ id_version }}
*{% if include_username or include_hostname %} generated by: {% if include_username %}{{ id_username }}{% endif %}{% if include_hostname %}@{{ id_hostname }}{% endif %}{% endif %}{% if include_timestamp %} at {{ id_timestamp }}{% endif %}
*/

#ifndef __{{ entity_name | upper }}_H__
#define __{{ entity_name | upper }}_H__

/* External to this header file, the base address for the register space need to be defined
#define {{ entity_name | upper }}_BASE_ADDR 0x00000000
*/

// Register Addresses
{% for reg in regs -%}
#define REG_{{ reg['name'] | upper }}_ADDR ({{ entity_name | upper }}_BASE_ADDR + {{ reg['addr_offset'] }})
{% endfor %}

// Shift / Mask values for packed registers
{% for reg in regs -%}
{% if reg['bits'] is integer -%}
{% elif reg['bits'] is mapping -%}
{% else -%}
{% for bit_field in reg['bits'] -%}
#define REG_{{ reg['name'] | upper }}_{{ bit_field['field_name'] | upper }}_MASK 0x{{ reg['bits']|get_mask(bit_field['field_name'],data_size) }}
#define REG_{{ reg['name'] | upper }}_{{ bit_field['field_name'] | upper }}_SHIFT {{ reg['bits']|get_offset(bit_field['field_name']) }}
{% endfor %}
{% endif %}
{% endfor %}

// Getter / Setter Macros
{% for reg in regs -%}
{% if reg['bits'] is integer -%}
{% elif reg['bits'] is mapping -%}
{% else -%}
{% for bit_field in reg['bits'] -%}
#define REG_{{ reg['name'] | upper }}_GET_{{ bit_field['field_name'] | upper }}(val) (((val) & REG_{{ reg['name'] | upper }}_{{ bit_field['field_name'] | upper }}_MASK) >> REG_{{ reg['name'] | upper }}_{{ bit_field['field_name'] | upper }}_SHIFT)
#define REG_{{ reg['name'] | upper }}_SET_{{ bit_field['field_name'] | upper }}(val) (((val) << REG_{{ reg['name'] | upper }}_{{ bit_field['field_name'] | upper }}_SHIFT) & REG_{{ reg['name'] | upper }}_{{ bit_field['field_name'] | upper }}_MASK)
{% endfor %}
{% endif %}
{% endfor %}

#endif