name: CI

on:
  push:
    branches:
      - main  # Run the tests on push to main branch
      - 17-verilog # temporary branch for testing verilog
  pull_request:
    branches:
      - main  # Run the tests on PRs to main branch
  schedule:
    - cron: "0 3 * * 0"

jobs:
  test_common:
    runs-on: ubuntu-latest  # This specifies the runner environment

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: pip install poetry && poetry install
    - name: Run tests
      run: poetry run pytest test/test_regdef.py test/test_argparse.py

  test_vhdl:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t ghdl-test -f Dockerfile.ghdl .

    - name: Run tests
      run: docker run ghdl-test poetry run pytest test/test_regdef.py test/test_argparse.py test/test_vhdl.py

  test_verilog:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t verilator-test -f Dockerfile.verilator .

    - name: Run tests
      run: docker run --entrypoint=poetry verilator run pytest test/test_regdef.py test/test_argparse.py test/test_verilog.py