name: CI

on:
  push:
    branches:
      - main  # Run the tests on push to main branch
      - 26-add-automated-testing-to-all-active-versions-of-python # temporary testing branch
  pull_request:
    branches:
      - main  # Run the tests on PRs to main branch
  schedule:
    - cron: "0 3 * * 0"

jobs:
  test_common:
    runs-on: ubuntu-latest  # This specifies the runner environment
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13']

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: pip install poetry && poetry install
    - name: Run tests
      run: poetry run pytest test/test_regdef.py test/test_argparse.py test/test_validate.py

  test_rtl:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t reg_test -f Dockerfile .

    - name: Run tests
      run: docker run reg_test poetry run pytest
